### ISSUE TITLE
Bug: @eslint/json ir returning an error when it parse package.json file

### ISSUE THREAD

**Issue by Byron2016** [eslint/json#31]
### Environment

**ESLint version**: 9.11.1
**@eslint/json version**: 9.11.1
**Node version**: v20.17.0
**npm version**: 10.8.3
**Operating System**: Windows 10 Pro 22H2 (19045.4894)

### Which language are you using?

json

### What did you do?

<details>
<summary>Configuration</summary>

**package.json**

```json
  {
    "name": "borrar_001",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "type": "module",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1",
      "inspector": "eslint --inspect-config",
      "lint": "eslint .",
      "lint:f": "eslint . --fix"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
      "@eslint/js": "^9.11.1",
      "@eslint/json": "^0.5.0",
      "@eslint/markdown": "^6.1.1",
      "eslint": "^9.11.1",
      "eslint-plugin-react": "^7.37.1",
      "globals": "^15.10.0",
      "typescript-eslint": "^8.8.0"
    }
  }
```

**eslint.config.mjs**

```js
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";
import pluginReact from "eslint-plugin-react";

import json from "@eslint/json";
import markdown from "@eslint/markdown";

export default [
  {
    ignores: ["node_modules", "dist"],
  },
  {
    plugins: {
      json,
      markdown,
    },
  },
  // lint JSON files
  {
    files: ["**/*.json"],
    language: "json/json",
    rules: {
      "json/no-duplicate-keys": "error",
      // "no-irregular-whitespace": "off",
    },
  },

  // lint MARKDOWN files
  {
    files: ["**/*.md"],
    plugins: {
      markdown,
    },
    language: "markdown/commonmark",
    rules: {
      "markdown/no-html": "error",
    },
  },
  { files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"] },
  { languageOptions: { globals: globals.browser } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  pluginReact.configs.flat.recommended,
];
```
</details>

```js
<!-- Paste your code here -->
```

### What did you expect to happen?

lint package.json without problem

### What actually happened?

**command executed**

`
pnpm run lint
` 

**Error message**

`
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .

Oops! Something went wrong! :(

ESLint: 9.11.1

TypeError: Error while loading rule 'no-irregular-whitespace': sourceCode.getAllComments is not a function
Occurred while linting C:\Users\user_01\borrar_001\package.json
    at Object.create (C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\rules\no-irregular-whitespace.js:87:41)
    at createRuleListeners (C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\linter\linter.js:943:21)
    at C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\linter\linter.js:1068:84
    at Array.forEach (<anonymous>)
    at runRules (C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\linter\linter.js:999:34)
    at #flatVerifyWithoutProcessors (C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\linter\linter.js:1914:31)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\linter\linter.js:1995:49)
    at Linter._verifyWithFlatConfigArray (C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\linter\linter.js:2084:21)
    at Linter.verify (C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\linter\linter.js:1528:61)
    at Linter.verifyAndFix (C:\Users\user_01\borrar_001\node_modules\.pnpm\eslint@9.11.1\node_modules\eslint\lib\linter\linter.js:2322:29)
 ELIFECYCLE  Command failed with exit code 2.
`

### Link to Minimal Reproducible Example

https://github.com/Byron2016/b_eslint_json_error_001

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bmeck** [comment]
Isn't no-irregular-whitespace a JS rule?

**Comment by Byron2016** [comment]
> Isn't no-irregular-whitespace a JS rule?

@bmeck if you comment eslint/json configuration section (eslint.config.mjs) the error dissapear, I think could exist a conflict with eslint?

**Comment by nzakas** [comment]
Yes, the problem is that you likely have a configuration object without a `files` key. Something like:

```js
{
    rules: {
        "no-irregular-whitespace": "error"
    }
}
```

That is then being merged into the configuration for JSON files and throwing an error because the JSON `SourceCode` does not contain the same methods as the JavaScript one.

It's likely one of the configs you're importing from `typescript-eslint` or `eslint-plugin-react`. Use `--inspect-config` to look closer and then [add a `files` key](https://eslint.org/docs/latest/use/configure/combine-configs#apply-a-config-array-to-a-subset-of-files) to any configs that aren't already using one.

**Comment by mbret** [comment]
I have the same problem and it is indeed coming from other packages such as eslint base and svelte. However, how are we supposed to handle it ? I don't seem to have problems with other plugins

**Comment by jerkovicl** [comment]
i have the issue as well, and i checked the config  with `--inspect-config` as @nzakas  suggested and everything looks fine and i have files declared for all custom stuff

**Comment by Byron2016** [comment]
@mbret @jerkovicl  This is my **eslint.config.mjs** file 
```js
import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";

import json from "@eslint/json";
import markdown from "@eslint/markdown";

export default [
  {
    ignores: ["node_modules", "dist"],
  },
  {
    plugins: {
      json,
      markdown,
    },
  },
  // lint JSON files
  {
    files: ["**/*.json"],
    language: "json/json",
    rules: {
      "json/no-duplicate-keys": "error",
    },
  },

  // lint MARKDOWN files
  ...markdown.configs.recommended,

  { files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"] },
  { languageOptions: { globals: globals.browser } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  //pluginReact.configs.flat.recommended,
  {
    name: "json-markdown-except-rules",
    files: ["**/*.json", "**/*.md"],
    rules: {
      "no-irregular-whitespace": "off",
    },
  },
];

```

I added this object: 
```js
// ....

import json from "@eslint/json";
import markdown from "@eslint/markdown";

export default [
  // ....
  {
    name: "json-markdown-except-rules",
    files: ["**/*.json", "**/*.md"],
    rules: {
      "no-irregular-whitespace": "off",
    },
  },
];

```

**Comment by jerkovicl** [comment]
@mbret ah I see , nice workaround there, thx for sharing.

My eslint config is bit bigger and part of NX monorepo

**Comment by matijs** [comment]
In our case it was our use of `@eslint/js` that was throwing a spanner in the works. Which, as both packages have the `@eslint` scope, feels maybe a bit odd.

This (a slight modification of the [getting started](https://eslint.org/docs/latest/use/getting-started#configuration) documentation):

```js
import json from '@eslint/json';
import js from '@eslint/js';

export default [
  {
    ignores: ['**/dist/']
  },
  js.configs.recommended,
  {
    files: ['**/*.json'],
    language: 'json/json',
    ...json.configs.recommended,
  },
];
```

Should be something like this

```js
import json from '@eslint/json';
import js from '@eslint/js';

export default [
  {
    ignores: ['**/dist/']
  },
  {
    files: ['**/*.js', '**/*.cjs', '**/*.mjs'],
    ...js.configs.recommended,
  },
  {
    files: ['**/*.json'],
    language: 'json/json',
    ...json.configs.recommended,
  },
];
```

when `@eslint/json` is used as well.
